In [40]:
import pandas as pd
from scipy.stats import ttest_ind

We read all data from our results and then run a t-test to calculate p values:

*Cells with ttest_ind show t-test results, all other cells load and aggregate data*

In [41]:
grouped_eeg_test = pd.read_csv('raw_out/grouped_eeg_test.csv')
grouped_eeg_test

CLF  accuracy        f1       auc
0  LogReg  0.639639  0.549046  0.625594
1     SVM  0.937515  0.930179  0.935286
2      rf  0.871463  0.846990  0.864651

In [42]:
grouped_occ_test = pd.read_csv('raw_out/grouped_occ_test.csv')
grouped_occ_test

CLF  accuracy        f1       auc
0  LogReg  0.988830  0.976284  0.990947
1     SVM  0.989216  0.977019  0.990962
2      rf  0.987674  0.973840  0.988691

In [43]:
grouped_lea_test = pd.read_csv('raw_out/grouped_lea_test.csv')
grouped_lea_test

CLF  accuracy        f1       auc
0  LogReg  0.731789  0.732046  0.731903
1     SVM  0.729207  0.728996  0.730008
2      rf  0.722771  0.717068  0.722585

In [44]:
grouped_csg_test = pd.read_csv('raw_out/grouped_csg_test.csv')
grouped_csg_test

CLF  accuracy        f1       auc
0  LogReg  0.744380  0.737894  0.697199
1     SVM  0.749534  0.755298  0.750471
2      rf  0.757065  0.760989  0.757471

In [45]:
data_lst = [grouped_eeg_test, grouped_occ_test, grouped_lea_test, grouped_csg_test]
clf_lst = ['LogReg', 'SVM', 'rf']

In [46]:
acc_log = [df.loc[df.CLF == 'LogReg'].accuracy.iloc[0] for df in data_lst]
acc_log

[0.6396392822265625,
 0.9888303399085998,
 0.7317892909049988,
 0.7443795323371887]

In [47]:
acc_svm = [df.loc[df.CLF == 'SVM'].accuracy.iloc[0] for df in data_lst]
acc_svm

[0.9375150442123412,
 0.9892159461975096,
 0.7292068004608154,
 0.7495341181755066]

In [48]:
acc_rf = [df.loc[df.CLF == 'rf'].accuracy.iloc[0] for df in data_lst]
acc_rf

[0.8714629292488099, 0.987673532962799, 0.7227710604667663, 0.7570649862289429]

In [49]:
f1_log = [df.loc[df.CLF == 'LogReg'].f1.iloc[0] for df in data_lst]
f1_log

[0.5490458015434354,
 0.9762835878902136,
 0.7320462028434845,
 0.7378938066944414]

In [50]:
f1_svm = [df.loc[df.CLF == 'SVM'].f1.iloc[0] for df in data_lst]
f1_svm

[0.9301786590785176, 0.977018850240397, 0.7289962376926, 0.7552975060344572]

In [51]:
f1_rf = [df.loc[df.CLF == 'rf'].f1.iloc[0] for df in data_lst]
f1_rf

[0.8469904103246033,
 0.9738399996677533,
 0.7170675655905128,
 0.7609887586248177]

In [52]:
auc_log = [df.loc[df.CLF == 'LogReg'].auc.iloc[0] for df in data_lst]
auc_log

[0.6255940589010951,
 0.9909466003165166,
 0.7319032230044098,
 0.6971988389303345]

In [53]:
auc_svm = [df.loc[df.CLF == 'SVM'].auc.iloc[0] for df in data_lst]
auc_svm

[0.9352864433090952,
 0.9909619919717556,
 0.7300075318890773,
 0.7504707870538188]

In [54]:
auc_rf = [df.loc[df.CLF == 'rf'].auc.iloc[0] for df in data_lst]
auc_rf

[0.8646511000085709, 0.9886908180404234, 0.7225847835761738, 0.757471216379867]

In [55]:
ttest_ind(acc_svm, acc_log).pvalue, ttest_ind(acc_rf, acc_svm).pvalue

(0.4779188385945048, 0.8579563749631394)

In [56]:
ttest_ind(f1_svm, f1_log).pvalue, ttest_ind(f1_rf, f1_svm).pvalue

(0.39160735851049266, 0.7919350355412891)

In [57]:
ttest_ind(auc_svm, auc_log).pvalue, ttest_ind(auc_svm, auc_rf).pvalue

(0.41495180227054596, 0.8432297673209298)

In [58]:
eeg_comb_test_df = pd.read_csv('raw_out/eeg_comb_test.csv').drop(columns = ['Unnamed: 0'])
occ_comb_test_df = pd.read_csv('raw_out/occ_comb_test.csv').drop(columns = ['Unnamed: 0'])
lea_comb_test_df = pd.read_csv('raw_out/lea_comb_test.csv').drop(columns = ['Unnamed: 0'])
csg_comb_test_df = pd.read_csv('raw_out/csg_comb_test.csv').drop(columns = ['Unnamed: 0'])

In [59]:
gr_eeg = eeg_comb_test_df.groupby('CLF').mean()
eeg_log = gr_eeg.loc['LogReg'].to_numpy()
eeg_log

array([0.63963928, 0.5490458 , 0.62559406])

In [60]:
gr_eeg = eeg_comb_test_df.groupby('CLF').mean()
eeg_svm = gr_eeg.loc['SVM'].to_numpy()
eeg_svm

array([0.93751504, 0.93017866, 0.93528644])

In [61]:
gr_eeg = eeg_comb_test_df.groupby('CLF').mean()
eeg_rf = gr_eeg.loc['rf'].to_numpy()
eeg_rf

array([0.87146293, 0.84699041, 0.8646511 ])

In [62]:
ttest_ind(eeg_svm, eeg_log).pvalue

0.000307975282383063

In [63]:
ttest_ind(eeg_svm, eeg_rf).pvalue

0.0006495468380593139

In [64]:
gr_occ = occ_comb_test_df.groupby('CLF').mean()
occ_log = gr_occ.loc['LogReg'].to_numpy()
occ_log

array([0.98883034, 0.97628359, 0.9909466 ])

In [65]:
gr_occ = occ_comb_test_df.groupby('CLF').mean()
occ_svm = gr_occ.loc['SVM'].to_numpy()
occ_svm

array([0.98921595, 0.97701885, 0.99096199])

In [66]:
gr_occ = occ_comb_test_df.groupby('CLF').mean()
occ_rf = gr_occ.loc['rf'].to_numpy()
occ_rf

array([0.98767353, 0.97384   , 0.98869082])

In [67]:
ttest_ind(occ_svm, occ_log).pvalue

0.9552160648387585

In [68]:
ttest_ind(occ_svm, occ_rf).pvalue

0.7378131284440838

In [69]:
gr_lea = lea_comb_test_df.groupby('CLF').mean()
lea_log = gr_lea.loc['LogReg'].to_numpy()
lea_log

array([0.73178929, 0.7320462 , 0.73190322])

In [70]:
gr_lea = lea_comb_test_df.groupby('CLF').mean()
lea_svm = gr_lea.loc['SVM'].to_numpy()
lea_svm

array([0.7292068 , 0.72899624, 0.73000753])

In [71]:
gr_lea = lea_comb_test_df.groupby('CLF').mean()
lea_rf = gr_lea.loc['rf'].to_numpy()
lea_rf

array([0.72277106, 0.71706757, 0.72258478])

In [81]:
ttest_ind(lea_svm, lea_log).pvalue

0.0013764133236427761

In [73]:
ttest_ind(lea_rf, lea_log).pvalue

0.0040503850577308514

In [74]:
gr_csg = csg_comb_test_df.groupby('CLF').mean()
csg_log = gr_csg.loc['LogReg'].to_numpy()
csg_log

array([0.74437953, 0.73789381, 0.69719884])

In [75]:
gr_csg = csg_comb_test_df.groupby('CLF').mean()
csg_svm = gr_csg.loc['SVM'].to_numpy()
csg_svm

array([0.74953412, 0.75529751, 0.75047079])

In [76]:
gr_csg = csg_comb_test_df.groupby('CLF').mean()
csg_rf = gr_csg.loc['rf'].to_numpy()
csg_rf

array([0.75706499, 0.76098876, 0.75747122])

In [77]:
ttest_ind(csg_rf, csg_log).pvalue

0.09680412660667899

In [39]:
ttest_ind(csg_rf, csg_svm).pvalue

0.0363591489784883